spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/DB_GARAGE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:thiago}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:thiago}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# application.properties
server.port=3003